import { Foodbank, FoodbankSubmission } from '@/types/foodbank';

export const mockFoodbanks: Foodbank[] = [
  // San Francisco Bay Area
  {
    id: '1',
    name: 'Community Food Pantry',
    address: '123 Main Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    lat: 37.7749,
    lng: -122.4194,
    phone: '(415) 555-0100',
    website: 'https://communityfoodpantry.org',
    hours: [
      { day: 'Monday', open: '09:00', close: '17:00' },
      { day: 'Wednesday', open: '09:00', close: '17:00' },
      { day: 'Friday', open: '09:00', close: '15:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'San Francisco County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: false,
      kosher: false,
      other: ['Baby formula', 'Pet food'],
    },
    lastVerified: '2024-01-15',
    queueNotes: 'Average wait time: 15-20 minutes. Arrive early for best selection.',
    requiredDocuments: ['Photo ID', 'Proof of address', 'Income verification'],
    isVerified: true,
    score: 95,
  },
  {
    id: '2',
    name: 'Helping Hands Food Bank',
    address: '456 Oak Avenue',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94103',
    lat: 37.7699,
    lng: -122.4094,
    phone: '(415) 555-0200',
    website: 'https://helpinghandsfoodbank.org',
    hours: [
      { day: 'Tuesday', open: '10:00', close: '18:00' },
      { day: 'Thursday', open: '10:00', close: '18:00' },
      { day: 'Saturday', open: '08:00', close: '14:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: false,
      halal: true,
      kosher: false,
    },
    lastVerified: '2024-01-20',
    queueNotes: 'No appointment needed. Queue forms at 9:30 AM.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 88,
  },
  {
    id: '3',
    name: 'City Mission Food Center',
    address: '789 Pine Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94108',
    lat: 37.7899,
    lng: -122.4094,
    phone: '(415) 555-0300',
    hours: [
      { day: 'Monday', open: '08:00', close: '16:00' },
      { day: 'Tuesday', open: '08:00', close: '16:00' },
      { day: 'Wednesday', open: '08:00', close: '16:00' },
      { day: 'Thursday', open: '08:00', close: '16:00' },
      { day: 'Friday', open: '08:00', close: '16:00' },
    ],
    requirements: {
      income: 'No income verification required',
      id: true,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: true,
      halal: false,
      kosher: true,
    },
    lastVerified: '2024-01-10',
    queueNotes: 'Long lines during lunch hours. Best time: 8:00-10:00 AM.',
    requiredDocuments: ['Photo ID'],
    isVerified: true,
    score: 92,
  },
  {
    id: '4',
    name: 'Faith Community Outreach',
    address: '321 Elm Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94110',
    lat: 37.7499,
    lng: -122.4194,
    phone: '(415) 555-0400',
    website: 'https://faithcommunityoutreach.org',
    hours: [
      { day: 'Wednesday', open: '13:00', close: '19:00' },
      { day: 'Saturday', open: '09:00', close: '13:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: false,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: false,
      other: ['Clothing', 'Hygiene kits'],
    },
    lastVerified: '2024-01-18',
    queueNotes: 'Hot meals served. Family-friendly environment.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 85,
  },
  {
    id: '5',
    name: 'Bay Area Emergency Food',
    address: '555 Market Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94105',
    lat: 37.7899,
    lng: -122.4000,
    phone: '(415) 555-0500',
    hours: [
      { day: 'Monday', open: '11:00', close: '15:00' },
      { day: 'Thursday', open: '11:00', close: '15:00' },
    ],
    requirements: {
      income: 'Below 150% federal poverty line',
      id: true,
      residency: 'Bay Area residents',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: true,
    },
    lastVerified: '2024-01-22',
    queueNotes: 'Limited capacity. Call ahead to confirm availability.',
    requiredDocuments: ['Photo ID', 'Proof of residency', 'Income statement'],
    isVerified: true,
    score: 78,
  },
  {
    id: '6',
    name: 'Oakland Food Connection',
    address: '1200 Broadway',
    city: 'Oakland',
    state: 'CA',
    zipCode: '94612',
    lat: 37.8044,
    lng: -122.2712,
    phone: '(510) 555-0100',
    website: 'https://oaklandfoodconnection.org',
    hours: [
      { day: 'Monday', open: '10:00', close: '18:00' },
      { day: 'Wednesday', open: '10:00', close: '18:00' },
      { day: 'Friday', open: '10:00', close: '18:00' },
    ],
    requirements: {
      income: 'Below 185% federal poverty line',
      id: true,
      residency: 'Alameda County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: false,
      other: ['Multilingual support', 'Home delivery for seniors'],
    },
    lastVerified: '2024-01-25',
    queueNotes: 'Pre-registration available online. Walk-ins welcome.',
    requiredDocuments: ['ID', 'Proof of income'],
    isVerified: true,
    score: 91,
  },
  {
    id: '7',
    name: 'Berkeley Community Pantry',
    address: '2020 University Avenue',
    city: 'Berkeley',
    state: 'CA',
    zipCode: '94704',
    lat: 37.8715,
    lng: -122.2730,
    phone: '(510) 555-0200',
    hours: [
      { day: 'Tuesday', open: '09:00', close: '15:00' },
      { day: 'Thursday', open: '09:00', close: '15:00' },
      { day: 'Saturday', open: '10:00', close: '14:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: true,
    },
    lastVerified: '2024-01-19',
    queueNotes: 'Student volunteers available to assist. Bike parking available.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 89,
  },
  
  // Los Angeles Area
  {
    id: '8',
    name: 'LA Central Food Depot',
    address: '1800 E 7th Street',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90021',
    lat: 34.0407,
    lng: -118.2468,
    phone: '(213) 555-0100',
    website: 'https://lacentralfood.org',
    hours: [
      { day: 'Monday', open: '08:00', close: '16:00' },
      { day: 'Tuesday', open: '08:00', close: '16:00' },
      { day: 'Wednesday', open: '08:00', close: '16:00' },
      { day: 'Thursday', open: '08:00', close: '16:00' },
      { day: 'Friday', open: '08:00', close: '14:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'Los Angeles County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: true,
      other: ['Spanish/English services'],
    },
    lastVerified: '2024-01-23',
    queueNotes: 'Large facility. Average wait: 30 minutes during peak hours.',
    requiredDocuments: ['Photo ID', 'Proof of address'],
    isVerified: true,
    score: 87,
  },
  {
    id: '9',
    name: 'Santa Monica Community Kitchen',
    address: '822 Lincoln Boulevard',
    city: 'Santa Monica',
    state: 'CA',
    zipCode: '90403',
    lat: 34.0195,
    lng: -118.4912,
    phone: '(310) 555-0100',
    hours: [
      { day: 'Monday', open: '11:00', close: '14:00' },
      { day: 'Wednesday', open: '11:00', close: '14:00' },
      { day: 'Friday', open: '11:00', close: '14:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: false,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: false,
      other: ['Hot meals served', 'Seating available'],
    },
    lastVerified: '2024-01-21',
    queueNotes: 'Meals served on-site. No takeaway containers.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 84,
  },
  {
    id: '10',
    name: 'Pasadena Food Alliance',
    address: '1744 E Washington Boulevard',
    city: 'Pasadena',
    state: 'CA',
    zipCode: '91104',
    lat: 34.1478,
    lng: -118.1165,
    phone: '(626) 555-0100',
    website: 'https://pasadenafoodalliance.org',
    hours: [
      { day: 'Tuesday', open: '10:00', close: '17:00' },
      { day: 'Thursday', open: '10:00', close: '17:00' },
      { day: 'Saturday', open: '09:00', close: '13:00' },
    ],
    requirements: {
      income: 'Below 150% federal poverty line',
      id: true,
      residency: 'San Gabriel Valley',
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: true,
      halal: false,
      kosher: false,
    },
    lastVerified: '2024-01-24',
    queueNotes: 'Appointments preferred. Walk-ins accepted based on capacity.',
    requiredDocuments: ['Photo ID', 'Income verification'],
    isVerified: true,
    score: 90,
  },

  // New York City Area
  {
    id: '11',
    name: 'Manhattan Food Bank',
    address: '39 Broadway',
    city: 'New York',
    state: 'NY',
    zipCode: '10006',
    lat: 40.7074,
    lng: -74.0113,
    phone: '(212) 555-0100',
    website: 'https://manhattanfoodbank.org',
    hours: [
      { day: 'Monday', open: '09:00', close: '18:00' },
      { day: 'Tuesday', open: '09:00', close: '18:00' },
      { day: 'Wednesday', open: '09:00', close: '18:00' },
      { day: 'Thursday', open: '09:00', close: '18:00' },
      { day: 'Friday', open: '09:00', close: '17:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'New York County',
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: true,
      halal: true,
      kosher: true,
      other: ['Multilingual staff'],
    },
    lastVerified: '2024-01-26',
    queueNotes: 'Very busy location. Online reservation system available.',
    requiredDocuments: ['ID', 'Proof of residency'],
    isVerified: true,
    score: 93,
  },
  {
    id: '12',
    name: 'Brooklyn Community Harvest',
    address: '135 Broadway',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '11211',
    lat: 40.7081,
    lng: -73.9571,
    phone: '(718) 555-0100',
    hours: [
      { day: 'Tuesday', open: '10:00', close: '16:00' },
      { day: 'Thursday', open: '10:00', close: '16:00' },
      { day: 'Saturday', open: '09:00', close: '15:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: true,
    },
    lastVerified: '2024-01-20',
    queueNotes: 'First-come, first-served. Bring reusable bags.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 88,
  },
  {
    id: '13',
    name: 'Queens Relief Center',
    address: '40-02 Queens Boulevard',
    city: 'Queens',
    state: 'NY',
    zipCode: '11104',
    lat: 40.7432,
    lng: -73.9196,
    phone: '(718) 555-0200',
    website: 'https://queensrelief.org',
    hours: [
      { day: 'Monday', open: '11:00', close: '19:00' },
      { day: 'Wednesday', open: '11:00', close: '19:00' },
      { day: 'Friday', open: '11:00', close: '19:00' },
    ],
    requirements: {
      income: 'Below 185% federal poverty line',
      id: true,
      residency: 'Queens County',
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: false,
      halal: true,
      kosher: false,
      other: ['Multiple language support'],
    },
    lastVerified: '2024-01-22',
    queueNotes: 'Evening hours available for working families.',
    requiredDocuments: ['ID', 'Proof of income'],
    isVerified: true,
    score: 86,
  },

  // Chicago Area
  {
    id: '14',
    name: 'Greater Chicago Food Depository',
    address: '4100 W Ann Lurie Place',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60632',
    lat: 41.8244,
    lng: -87.7254,
    phone: '(773) 555-0100',
    website: 'https://chicagofooddepository.org',
    hours: [
      { day: 'Monday', open: '08:30', close: '17:00' },
      { day: 'Tuesday', open: '08:30', close: '17:00' },
      { day: 'Wednesday', open: '08:30', close: '17:00' },
      { day: 'Thursday', open: '08:30', close: '17:00' },
      { day: 'Friday', open: '08:30', close: '16:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'Cook County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: false,
    },
    lastVerified: '2024-01-25',
    queueNotes: 'Large distribution center. Parking available.',
    requiredDocuments: ['Photo ID', 'Proof of address'],
    isVerified: true,
    score: 94,
  },
  {
    id: '15',
    name: 'Lakeview Pantry',
    address: '3945 N Sheridan Road',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60613',
    lat: 41.9541,
    lng: -87.6553,
    phone: '(773) 555-0200',
    hours: [
      { day: 'Tuesday', open: '10:00', close: '18:00' },
      { day: 'Wednesday', open: '10:00', close: '18:00' },
      { day: 'Saturday', open: '09:00', close: '14:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: true,
      halal: false,
      kosher: true,
    },
    lastVerified: '2024-01-18',
    queueNotes: 'Client choice model - select your own items.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 91,
  },

  // Houston Area
  {
    id: '16',
    name: 'Houston Food Bank',
    address: '535 Portwall Street',
    city: 'Houston',
    state: 'TX',
    zipCode: '77029',
    lat: 29.7604,
    lng: -95.3698,
    phone: '(713) 555-0100',
    website: 'https://houstonfoodbank.org',
    hours: [
      { day: 'Monday', open: '09:00', close: '17:00' },
      { day: 'Tuesday', open: '09:00', close: '17:00' },
      { day: 'Wednesday', open: '09:00', close: '17:00' },
      { day: 'Thursday', open: '09:00', close: '17:00' },
      { day: 'Friday', open: '09:00', close: '17:00' },
    ],
    requirements: {
      income: 'Below 150% federal poverty line',
      id: true,
      residency: 'Harris County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: false,
      other: ['Nutrition education', 'Senior programs'],
    },
    lastVerified: '2024-01-27',
    queueNotes: 'One of the largest food banks in the country. Multiple distribution points.',
    requiredDocuments: ['ID', 'Proof of residency', 'Income statement'],
    isVerified: true,
    score: 96,
  },
  {
    id: '17',
    name: 'North Houston Community Pantry',
    address: '1314 Greens Road',
    city: 'Houston',
    state: 'TX',
    zipCode: '77032',
    lat: 29.9158,
    lng: -95.4211,
    phone: '(281) 555-0100',
    hours: [
      { day: 'Wednesday', open: '10:00', close: '14:00' },
      { day: 'Saturday', open: '09:00', close: '13:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: false,
      halal: false,
      kosher: false,
    },
    lastVerified: '2024-01-16',
    queueNotes: 'Drive-through service available.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 82,
  },

  // Phoenix Area
  {
    id: '18',
    name: 'St. Mary\'s Food Bank',
    address: '2831 N 31st Avenue',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85009',
    lat: 33.4752,
    lng: -112.1187,
    phone: '(602) 555-0100',
    website: 'https://stmarysfoodbank.org',
    hours: [
      { day: 'Monday', open: '08:00', close: '16:00' },
      { day: 'Tuesday', open: '08:00', close: '16:00' },
      { day: 'Wednesday', open: '08:00', close: '16:00' },
      { day: 'Thursday', open: '08:00', close: '16:00' },
      { day: 'Friday', open: '08:00', close: '16:00' },
    ],
    requirements: {
      income: 'No income verification required',
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: true,
      halal: false,
      kosher: false,
      other: ['Mobile pantry program'],
    },
    lastVerified: '2024-01-24',
    queueNotes: 'America\'s first food bank. Air-conditioned waiting area.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 95,
  },
  {
    id: '19',
    name: 'Phoenix Rescue Mission',
    address: '1801 S 35th Avenue',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85009',
    lat: 33.4355,
    lng: -112.1360,
    phone: '(602) 555-0200',
    hours: [
      { day: 'Monday', open: '11:00', close: '13:00' },
      { day: 'Tuesday', open: '11:00', close: '13:00' },
      { day: 'Wednesday', open: '11:00', close: '13:00' },
      { day: 'Thursday', open: '11:00', close: '13:00' },
      { day: 'Friday', open: '11:00', close: '13:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: false,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: false,
      other: ['Clothing', 'Shower facilities'],
    },
    lastVerified: '2024-01-19',
    queueNotes: 'Hot meals served daily. Chapel service optional.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 81,
  },

  // Philadelphia Area
  {
    id: '20',
    name: 'Philabundance',
    address: '3616 S Galloway Street',
    city: 'Philadelphia',
    state: 'PA',
    zipCode: '19148',
    lat: 39.9137,
    lng: -75.1459,
    phone: '(215) 555-0100',
    website: 'https://philabundance.org',
    hours: [
      { day: 'Monday', open: '09:00', close: '17:00' },
      { day: 'Tuesday', open: '09:00', close: '17:00' },
      { day: 'Wednesday', open: '09:00', close: '17:00' },
      { day: 'Thursday', open: '09:00', close: '17:00' },
      { day: 'Friday', open: '09:00', close: '16:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'Philadelphia County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: true,
    },
    lastVerified: '2024-01-26',
    queueNotes: 'Network of partner agencies throughout the region.',
    requiredDocuments: ['ID', 'Proof of address'],
    isVerified: true,
    score: 92,
  },
  {
    id: '21',
    name: 'Broad Street Ministry',
    address: '315 S Broad Street',
    city: 'Philadelphia',
    state: 'PA',
    zipCode: '19107',
    lat: 39.9481,
    lng: -75.1652,
    phone: '(215) 555-0200',
    hours: [
      { day: 'Monday', open: '11:00', close: '14:00' },
      { day: 'Wednesday', open: '11:00', close: '14:00' },
      { day: 'Friday', open: '11:00', close: '14:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: false,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: false,
      other: ['Social services', 'Medical clinic'],
    },
    lastVerified: '2024-01-21',
    queueNotes: 'Sit-down restaurant-style dining. Dignity-focused service.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 87,
  },

  // Seattle Area
  {
    id: '22',
    name: 'Seattle Food Bank',
    address: '1531 Western Avenue',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    lat: 47.6097,
    lng: -122.3384,
    phone: '(206) 555-0100',
    website: 'https://seattlefoodbank.org',
    hours: [
      { day: 'Tuesday', open: '10:00', close: '18:00' },
      { day: 'Wednesday', open: '10:00', close: '18:00' },
      { day: 'Thursday', open: '10:00', close: '18:00' },
      { day: 'Saturday', open: '09:00', close: '15:00' },
    ],
    requirements: {
      income: 'Below 185% federal poverty line',
      id: true,
      residency: 'King County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: false,
      other: ['Client choice shopping'],
    },
    lastVerified: '2024-01-25',
    queueNotes: 'Wheelchair accessible. Bus stop nearby.',
    requiredDocuments: ['ID', 'Proof of income'],
    isVerified: true,
    score: 90,
  },
  {
    id: '23',
    name: 'Rainier Valley Food Bank',
    address: '3800 S McClellan Street',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98118',
    lat: 47.5569,
    lng: -122.2877,
    phone: '(206) 555-0200',
    hours: [
      { day: 'Monday', open: '13:00', close: '19:00' },
      { day: 'Tuesday', open: '10:00', close: '16:00' },
      { day: 'Thursday', open: '10:00', close: '16:00' },
      { day: 'Friday', open: '10:00', close: '16:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: true,
      preparedMeals: true,
      diapers: false,
      halal: true,
      kosher: false,
      other: ['Culturally diverse food options'],
    },
    lastVerified: '2024-01-20',
    queueNotes: 'Multilingual services available.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 88,
  },

  // Boston Area
  {
    id: '24',
    name: 'Greater Boston Food Bank',
    address: '70 South Bay Avenue',
    city: 'Boston',
    state: 'MA',
    zipCode: '02118',
    lat: 42.3360,
    lng: -71.0640,
    phone: '(617) 555-0100',
    website: 'https://gbfb.org',
    hours: [
      { day: 'Monday', open: '09:00', close: '17:00' },
      { day: 'Tuesday', open: '09:00', close: '17:00' },
      { day: 'Wednesday', open: '09:00', close: '17:00' },
      { day: 'Thursday', open: '09:00', close: '17:00' },
      { day: 'Friday', open: '09:00', close: '17:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'Suffolk County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: true,
    },
    lastVerified: '2024-01-27',
    queueNotes: 'Network hub serving 190 partner agencies.',
    requiredDocuments: ['ID', 'Proof of residency'],
    isVerified: true,
    score: 94,
  },
  {
    id: '25',
    name: 'Cambridge Community Kitchen',
    address: '99 Bishop Allen Drive',
    city: 'Cambridge',
    state: 'MA',
    zipCode: '02139',
    lat: 42.3736,
    lng: -71.1097,
    phone: '(617) 555-0200',
    hours: [
      { day: 'Wednesday', open: '12:00', close: '14:00' },
      { day: 'Friday', open: '12:00', close: '14:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: false,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: false,
      other: ['Take-home meals available'],
    },
    lastVerified: '2024-01-18',
    queueNotes: 'Small but welcoming community space.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 83,
  },

  // Denver Area
  {
    id: '26',
    name: 'Food Bank of the Rockies',
    address: '10700 E 45th Avenue',
    city: 'Denver',
    state: 'CO',
    zipCode: '80239',
    lat: 39.7797,
    lng: -104.8686,
    phone: '(303) 555-0100',
    website: 'https://foodbankrockies.org',
    hours: [
      { day: 'Monday', open: '08:00', close: '16:00' },
      { day: 'Tuesday', open: '08:00', close: '16:00' },
      { day: 'Wednesday', open: '08:00', close: '16:00' },
      { day: 'Thursday', open: '08:00', close: '16:00' },
      { day: 'Friday', open: '08:00', close: '16:00' },
    ],
    requirements: {
      income: 'Below 185% federal poverty line',
      id: true,
      residency: 'Denver County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: false,
      kosher: false,
      other: ['Mobile pantry', 'Kid\'s Cafe'],
    },
    lastVerified: '2024-01-26',
    queueNotes: 'Serving Colorado and Wyoming. Check website for mobile locations.',
    requiredDocuments: ['ID', 'Proof of income'],
    isVerified: true,
    score: 93,
  },
  {
    id: '27',
    name: 'Denver Rescue Mission',
    address: '6100 Smith Road',
    city: 'Denver',
    state: 'CO',
    zipCode: '80207',
    lat: 39.7879,
    lng: -104.9028,
    phone: '(303) 555-0200',
    hours: [
      { day: 'Monday', open: '11:30', close: '13:00' },
      { day: 'Tuesday', open: '11:30', close: '13:00' },
      { day: 'Wednesday', open: '11:30', close: '13:00' },
      { day: 'Thursday', open: '11:30', close: '13:00' },
      { day: 'Friday', open: '11:30', close: '13:00' },
    ],
    requirements: {
      id: false,
      residency: undefined,
    },
    services: {
      freshProduce: false,
      preparedMeals: true,
      diapers: false,
      halal: false,
      kosher: false,
      other: ['Shelter services', 'Recovery programs'],
    },
    lastVerified: '2024-01-22',
    queueNotes: 'Hot meal service. Chapel attendance encouraged but not required.',
    requiredDocuments: ['None required'],
    isVerified: true,
    score: 80,
  },

  // Atlanta Area
  {
    id: '28',
    name: 'Atlanta Community Food Bank',
    address: '732 Joseph E Lowery Boulevard NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30318',
    lat: 33.7677,
    lng: -84.4134,
    phone: '(404) 555-0100',
    website: 'https://acfb.org',
    hours: [
      { day: 'Monday', open: '09:00', close: '17:00' },
      { day: 'Tuesday', open: '09:00', close: '17:00' },
      { day: 'Wednesday', open: '09:00', close: '17:00' },
      { day: 'Thursday', open: '09:00', close: '17:00' },
      { day: 'Friday', open: '09:00', close: '16:00' },
    ],
    requirements: {
      income: 'Below 200% federal poverty line',
      id: true,
      residency: 'Metro Atlanta',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: false,
      other: ['SNAP assistance', 'Nutrition education'],
    },
    lastVerified: '2024-01-25',
    queueNotes: 'Serving 29 counties. Partner agencies throughout region.',
    requiredDocuments: ['Photo ID', 'Proof of address'],
    isVerified: true,
    score: 91,
  },
  {
    id: '29',
    name: 'North Fulton Community Charities',
    address: '11270 Elkins Road',
    city: 'Roswell',
    state: 'GA',
    zipCode: '30076',
    lat: 34.0437,
    lng: -84.3097,
    phone: '(770) 555-0100',
    hours: [
      { day: 'Tuesday', open: '09:00', close: '15:00' },
      { day: 'Wednesday', open: '09:00', close: '15:00' },
      { day: 'Thursday', open: '09:00', close: '15:00' },
    ],
    requirements: {
      income: 'Below 150% federal poverty line',
      id: true,
      residency: 'North Fulton County',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: false,
      kosher: false,
      other: ['Financial assistance', 'Thrift store'],
    },
    lastVerified: '2024-01-19',
    queueNotes: 'Appointment required. Call ahead.',
    requiredDocuments: ['ID', 'Proof of income', 'Proof of residency'],
    isVerified: true,
    score: 85,
  },

  // Miami Area
  {
    id: '30',
    name: 'Feeding South Florida',
    address: '4925 N Perry Drive',
    city: 'Pembroke Park',
    state: 'FL',
    zipCode: '33023',
    lat: 25.9856,
    lng: -80.1856,
    phone: '(954) 555-0100',
    website: 'https://feedingsouthflorida.org',
    hours: [
      { day: 'Monday', open: '08:30', close: '17:00' },
      { day: 'Tuesday', open: '08:30', close: '17:00' },
      { day: 'Wednesday', open: '08:30', close: '17:00' },
      { day: 'Thursday', open: '08:30', close: '17:00' },
      { day: 'Friday', open: '08:30', close: '16:00' },
    ],
    requirements: {
      income: 'Below 185% federal poverty line',
      id: true,
      residency: 'Broward, Miami-Dade, Monroe, Palm Beach counties',
    },
    services: {
      freshProduce: true,
      preparedMeals: false,
      diapers: true,
      halal: true,
      kosher: false,
      other: ['Spanish/English/Creole services'],
    },
    lastVerified: '2024-01-27',
    queueNotes: 'One of the largest food banks in Florida. Multiple distribution sites.',
    requiredDocuments: ['ID', 'Proof of income'],
    isVerified: true,
    score: 95,
  },
];

export const mockSubmissions: FoodbankSubmission[] = [];